# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            -  trattativa_centrofriuli-network
#        depends_on:
#            - mysql
#    mysql:
#        image: mysql:5.7
#        volumes:
#            - ./data/mysql:/var/lib/mysql
#        restart: unless-stopped
#        tty: true
#        ports:
#            - "3308:3306"
#        environment:
#            MYSQL_DATABASE: '${DB_DATABASE}'
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_USER: '${DB_USERNAME}'
#        networks:
#            - sail
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        links:
#            - mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            PMA_USER: 'root'
#            PMA_PASSWORD: '${DB_PASSWORD}'
#            PMA_HOST: mysql
#            PMA_ARBITRARY: 1
#        restart: always
#        ports:
#            - "8085:80"
#        networks:
#            - sail
networks:
    trattativa_centrofriuli-network:
        driver: default
        external: true
